name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua/ plugin/
